version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: todo_notes_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: todo_notes
      POSTGRES_USER: todouser
      POSTGRES_PASSWORD: your_secure_password_here
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - todo_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todouser -d todo_notes"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local

networks:
  todo_network:
    driver: bridge
